% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\renewcommand{\baselinestretch}{1.1}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{makecell}
\usepackage{pdflscape}
\usepackage{float}
\usepackage{fancyhdr}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={LDA Homework 2 (2025-2026)},
  pdfauthor={Anita Kerubo Ogero (2469491); Okolie Tess Eucharia (2468507); Moses Mburu (2469245); Dorothy Chepkoech (2469284)},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{LDA Homework 2 (2025-2026)}
\author{Anita Kerubo Ogero (2469491) \and Okolie Tess Eucharia
(2468507) \and Moses Mburu (2469245) \and Dorothy Chepkoech (2469284)}
\date{}

\begin{document}
\maketitle


\subsubsection{Question 1}\label{question-1}

\paragraph{Exploratory Data Analysis/Data
Description}\label{exploratory-data-analysisdata-description}

At baseline (Figure~\ref{fig-cdrsb-by-time}), most patients have
\(\text{CDRSBbin}=0\) (\(\text{CDRSB} \le 10\)), about 75--80\% are in
the mild group (CDRSBbin=0) and only about 20--25\% already have
\(\text{CDRSB} > 10\). Over time the bars shift: by visit 6--7, around
65--70\% of the observed patients have \(\text{CDRSBbin}=1\), so a much
larger share has moved into the more severe category.

The sex plot reflect the above pattern. At the first visit, the
proportion with \(\text{CDRSB} > 10\) is low in both sexes (around
10--15\%), with males slightly higher than females. As time goes on, the
lines rise and come together; by visits 6--7 both sexes have roughly
60--70\% of patients above the cut-off, so among those who remain there
is no strong or persistent sex imbalance in severity.

\begin{figure}[H]

\centering{

\includegraphics{lda_homework2_2025_files/figure-pdf/fig-cdrsb-by-time-1.pdf}

}

\caption{\label{fig-cdrsb-by-time}Distribution of CDRSB Scores Over Time
and by sex}

\end{figure}%

The age and BMI boxplots in Figure~\ref{fig-age-bmi-by-cdrsb} give a
cross-sectional picture at each visit. At every time point, patients
with \(\text{CDRSBbin}=1\) are on average a few years older than those
with \(\text{CDRSBbin}=0\) (median ages mostly in the late 60s to low
70s), but this age gap becomes smaller over time. In the early visits we
still see very old patients (some above 85 years), whereas by visits
6--7 these extreme ages have largely disappeared and most patients
cluster around their late 60s--early 70s. BMI medians stay around 25--27
kg/m(\^{}2) and the two CDRSB groups have very similar BMI distributions
at all visits.

These plots describe only patients who are still observed at each visit.
From Homework 1 we saw that older patients tend to drop out earlier.

In summary, from the exploratory
figures(Figure~\ref{fig-cdrsb-by-time},Figure~\ref{fig-age-bmi-by-cdrsb}
and Figure~\ref{fig-age-bmi-by-cdrsb}), sex, age and BMI appear to be
related to both the outcome and the biomarkers, so they are potential
confounders. The plots show that the proportion with CDRSBbin = 1
differs slightly by sex, and that patients with CDRSBbin = 0 are on
average slightly older than those with CDRSBbin = 1, while BMI
distributions are broadly similar across outcome groups but remain in a
range where BMI is clinically relevant. To reduce confounding and
isolate the associations of ADL, ABPET and TAUPET with CDRSBbin, we
therefore adjust for sex, age and BMI in the model.

\begin{figure}[H]

\centering{

\includegraphics{lda_homework2_2025_files/figure-pdf/fig-age-bmi-by-cdrsb-1.pdf}

}

\caption{\label{fig-age-bmi-by-cdrsb}Distribution of Age and BMI by
CDRSBbin}

\end{figure}%

\begin{figure}[H]

\centering{

\includegraphics{lda_homework2_2025_files/figure-pdf/fig-retention-rate-high-cdrsb-1.pdf}

}

\caption{\label{fig-retention-rate-high-cdrsb}Retention Rate Over Time
for Patients with High CDRSB (\textgreater10) at Baseline}

\end{figure}%

\begin{figure}[H]

\centering{

\includegraphics{lda_homework2_2025_files/figure-pdf/fig-semi-variogram-1.pdf}

}

\caption{\label{fig-semi-variogram}Empirical Semivariogram of CDRSBbin
Over Time}

\end{figure}%

To estimate how the population averaged (marginal effects) probability
of being in the worse cognitive category (CDRSBbin = 1, i.e.~CDRSB
\textgreater{} 10) changes over time, we fitted a marginal model using
generalized estimating equations (GEE), GEE1 with a logit link and an
AR(1) working correlation structure with a robust sandwich standard
errors.We modelled the longitudinal binary outcome CDRSBbin as a
function of time, sex, age, body mass index (BMI), baseline ADL, and the
time-varying biomarkers ABPET and TAUPET. In addition, we included
interactions between time and ABPET, and between time and TAUPET, to
allow the effects of these biomarkers on the probability of worse
cognition to change over time. The fitted model also accounts for
within-patient correlation across repeated visits using the working
correlation matrix.

Let \(Y_{it}\) be the binary outcome for patient \(i\) at time \(t\). We
define the marginal mean as: \[
\pi_{it} = \Pr\bigl(Y_{it} = 1 \mid X_{it}\bigr).
\] where \(X_{it}\) denotes the vector of covariates for patient \(i\)
at time \(t\). We specify the marginal mean model with a logit link as:
\[
\begin{aligned}
\text{logit}(\pi_{it}) 
=
\beta_0 
+ \beta_1\,\text{time}_{it}
+ \beta_2\,\text{sex}_i
+ \beta_3\,\text{age}_i
+ \beta_4\,\text{bmi}_i
+ \beta_5\,\text{adl}_i
+ \beta_6\,\text{abpet}_{it} \\
+ \beta_7\,\text{taupet}_{it}
+ \beta_8\,\bigl(\text{time}_{it}\cdot \text{abpet}_{it}\bigr)
+ \beta_9\,\bigl(\text{time}_{it}\cdot \text{taupet}_{it}\bigr),
\end{aligned}
\] where: \[
\pi_{it} = \Pr(Y_{it} = 1)
\quad \text{and} \quad
\text{logit}(\pi_{it}) = \log\left\{\frac{\pi_{it}}{1 - \pi_{it}}\right\}.
\] The parameters \(\beta_0,\dots,\beta_9\) are regression coefficients:
each \(\beta_k\) represents the change in the marginal log-odds of
having CDRSBbin = 1 associated with a one-unit increase in the
corresponding covariate (or interaction term), holding the other
covariates fixed. For the binary outcome(CDRSBbin), the marginal
variance is : \[
{Var}(Y_{it} \mid X_{it}) = \pi_{it}\bigl(1 - \pi_{it}\bigr) 
\] For this GEE model, the working correlation matrix for patient \(i\)
is \[
\mathbf{V}_i(\beta, \alpha, \phi)
=
\phi\,\mathbf{A}_i^{1/2}(\beta)\,
\mathbf{R}_i(\alpha)\,
\mathbf{A}_i^{1/2}(\beta),
\]

where \(\phi\) is a dispersion parameter which is estimated from pearson
residuals as: \[
\hat{\phi}
=
\frac{1}{N}
\sum_{i=1}^N
\left\{
\frac{1}{n_i}
\sum_{j=1}^{n_i} e_{ij}^2
\right\},
\] where \(N\) is the number of subjects, \(n_i\) is the number of
observations for patient \(i\), and \[
e_{ij} = \frac{y_{ij} - \mu_{ij}}{\sqrt{v(\mu_{ij})}}
\] are the Pearson residuals. Here \(\mu_{ij}\) is the fitted mean and
\(v(\mu_{ij})\) is the GLM variance function (for a binary
outcome(CDRSBbin), \(v(\mu_{ij}) = \mu_{ij}(1-\mu_{ij})\)). For the
binary outcome we set the dispersion parameter \(\phi = 1\), as is
standard for the binomial model. \(\mathbf{A}_i(\beta)\) is a diagonal
matrix with entries: \[
\operatorname{Var}(Y_{it} \mid X_{it}) = \pi_{it}\bigl(1 - \pi_{it}\bigr),
\] and \({R}(\alpha)\) is the AR(1) correlation matrix with
\(\text{Corr}(Y_{it}, Y_{is}) = \alpha^{|t-s|}\),for measurements \(t\)
and \(s\) on the same patient. For this AR(1) working correlation, the
correlation parameter \(\alpha\) is estimated from the Pearson residuals
as: \[
\hat{\alpha}
=
\frac{1}{N}
\sum_{i=1}^N
\left\{
\frac{1}{n_i - 1}
\sum_{j=1}^{n_i - 1} e_{ij}\,e_{i,j+1}
\right\},
\] where \(N\) is the number of subjects and \(n_i\) is the number of
observations for subject \(i\). Thus, for each subject we compute the
average product of Pearson residuals from adjacent time points, and then
we average these quantities over all subjects to obtain moment based
\(\hat{\alpha}\), which is used to construct the AR(1) working
correlation matrix. Finally, we applied robust (``sandwich'') standard
errors that inference remains valid even if the working correlation is
misspecified.

\begin{verbatim}

Call:
geeglm(formula = CDRSBbin ~ time + sex + age + bmi + adl + abpet + 
    taupet + time:adl + time:abpet + time:taupet, family = binomial(link = "logit"), 
    data = alzheimer_long, id = patid, corstr = "ar1", std.err = "san.se")

 Coefficients:
             Estimate   Std.err  Wald Pr(>|W|)   
(Intercept)  1.100634  1.300470 0.716  0.39737   
time        -0.280726  0.233360 1.447  0.22899   
sexFemale   -0.095732  0.057213 2.800  0.09427 . 
age         -0.012545  0.007103 3.120  0.07735 . 
bmi          0.006353  0.012483 0.259  0.61080   
adl         -0.035722  0.030842 1.341  0.24677   
abpet        0.187326  0.203704 0.846  0.35778   
taupet      -0.975639  0.580008 2.829  0.09255 . 
time:adl     0.006924  0.007507 0.851  0.35635   
time:abpet  -0.051521  0.049281 1.093  0.29581   
time:taupet  0.304144  0.111800 7.401  0.00652 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = ar1 
Estimated Scale Parameters:

            Estimate Std.err
(Intercept)   0.9912 0.01877
  Link = identity 

Estimated Correlation Parameters:
      Estimate Std.err
alpha   0.3094 0.01265
Number of clusters:   1253  Maximum cluster size: 7 
\end{verbatim}

\begin{table}
\caption{GEE Model Results (Odds Ratios)}\tabularnewline

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lcccc}
\toprule
term & estimate & std.error & statistic & p.value\\
\midrule
(Intercept) & 3.01 [0.23, 38.46] & 1.30 & 0.72 & 0.40\\
time & 0.76 [0.48, 1.19] & 0.23 & 1.45 & 0.23\\
sexFemale & 0.91 [0.81, 1.02] & 0.06 & 2.80 & 0.09\\
age & 0.99 [0.97, 1.00] & 0.01 & 3.12 & 0.08\\
bmi & 1.01 [0.98, 1.03] & 0.01 & 0.26 & 0.61\\
\addlinespace
adl & 0.96 [0.91, 1.03] & 0.03 & 1.34 & 0.25\\
abpet & 1.21 [0.81, 1.80] & 0.20 & 0.85 & 0.36\\
taupet & 0.38 [0.12, 1.17] & 0.58 & 2.83 & 0.09\\
time:adl & 1.01 [0.99, 1.02] & 0.01 & 0.85 & 0.36\\
time:abpet & 0.95 [0.86, 1.05] & 0.05 & 1.09 & 0.30\\
\addlinespace
time:taupet & 1.36 [1.09, 1.69] & 0.11 & 7.40 & <0.01\\
\bottomrule
\end{tabular}}
\endgroup{}
\end{table}

\textbf{Model Motivation}

We used a marginal logistic model fitted by generalized estimating
equations (GEE1) because our interest was in population-averaged effects
rather than individual patient trajectories. In particular, we wanted to
answer: on average, how do time, ADL, ABPET and TAUPET affect the
probability of worse cognition after adjusting for sex, age and BMI? The
outcome CDRSBbin is binary, so a binomial model with a logit link is
appropriate and allows us to express effects as log-odds ratios (and
odds ratios) for the probability of CDRSBbin = 1.

Because we have repeated measurements from the same patients, the
observations are correlated. The semivariogram indicated that
within-patient correlation decreases as the time lag increases,
suggesting an AR(1) pattern. To reflect this, we specified an AR(1)
working correlation structure, in which measurements closer in time
within a patient are more correlated than those further apart. The
correlation parameter is estimated from the Pearson residuals and used
to build the working covariance matrices.

We use the GEE1 formulation to model only the marginal mean \$
E(Y\_\{it\} \mid X\_\{it\}) = \pi\_\{it\}\$ with a logit link, and treat
the within-patient correlation as a working feature rather than a
primary target of inference. This is appropriate because our scientific
question concerns the marginal mean as a function of the covariates.
GEE1 directly targets this mean and treats the working correlation as a
nuisance component. We report robust (sandwich) standard errors for the
regression coefficients; these remain valid even if the AR(1) working
correlation is misspecified, provided the mean model is correct and
missingness is at least missing at random.

Additionally, we did not use GEE2 or alternating logistic regression
because our main goal was to model the average probability of worse
cognition, not the association between pairs of measurements within a
patient. GEE2/ALR would add extra parameters for within-patient
association (pairwise log-odds ratios) that are harder to interpret here
and less stable given the sample size. Also we did not use transition,
Bahadur or log-linear models, which focus on the full joint or
conditional structure of the repeated outcomes (e.g.~how each visit
depends on the previous one) and do not give parameters that map as
directly to the average risk at a given time. In contrast, GEE1 directly
models the marginal mean of the binary outcome with a logistic link,
provides population-averaged effects of time, ADL, ABPET and TAUPET, and
uses a working correlation only to account for within-patient
dependence, combined with sandwich standard errors for robust inference.

\textbf{Choice of method and Estimation}

The regression parameters \(\beta\) were obtained by solving the GEE
using an iterative algorithm, and the AR(1) correlation parameter
\(\alpha\) was estimated from the Pearson residuals using
method-of-moments. We report robust (sandwich) standard errors for
\(\hat_beta\), which give valid inference for the marginal mean model
even if the working correlation is not correctly specified, provided the
mean model is correctly specified and the missing data mechanism is at
least missing at random.

\textbf{Assumptions}

\begin{itemize}
\item
  Correct mean model: The marginal mean of the binary outcome is
  correctly specified as
  \(\text{logit}\{\Pr(Y_{it} = 1 \mid X_{it})\} = X_{it}^\top \beta,\)
  with the chosen covariates (time, sex, age, BMI, ADL, ABPET, TAUPET
  and their interactions with time) and a logit link.
\item
  Appropriate variance function: Conditional on the covariates,
  \(Y_{it}\) follows a Bernoulli distribution with variance \$
  \operatorname{Var}(Y\_\{it\} \mid X\_\{it\}) = \pi\emph{\{it\}\bigl(1
  - \pi}\{it\}\bigr),\$ where
  \(\pi_{it} = \Pr(Y_{it} = 1 \mid X_{it})\).
\item
  Independence of clusters: Different patients (and trials) are
  independent. Correlation is only present between repeated measurements
  from the same patient.
\end{itemize}

\textbf{Advantages}

\begin{itemize}
\tightlist
\item
  The estimators \(\hat{\beta}\) are consistent even if the working
  correlation matrix is incorrect.
\item
  Directly answers population-level questions (``on average in this
  population, how does the probability of worse cognition change with
  time and clinical variables( adl, taupet and abpet)'').
\item
  The GEE estimator \(\hat{\beta}\) is asymptoticaly normal: for a large
  number of subjects, its sampling distribution is approximately
  multivariate normal with mean equal to the true \({\beta}\) and
  covariance given by the sandwich(robust) variance even if the working
  correlation matrix is misspecified.
\item
  With GEE, the robust (`sandwich') standard errors are asymptotically
  valid even if the working correlation structure is misspecified.
\item
  Handles unbalanced follow-up and missing visits reasonably well,
  assuming missing at random given covariates.
\end{itemize}

\textbf{Disadvantages}

\begin{itemize}
\tightlist
\item
  A bad choice for working correlation matrix affect the efficiency for
  \(\hat{\beta})\)
\item
  GEE does not model patient-specific effects; no individual
  trajectories. so, interpretation is population-average, not
  subject-specific.
\item
  If dropout depends strongly on unobserved severity, MAR assumption may
  be violated.
\end{itemize}

\textbf{Reflection on Parameterization}

\begin{itemize}
\tightlist
\item
  Link function: The logit link gives coefficients that are log--odds
  ratios at the population level, which are easy to interpret for a
  clinician
\item
  Baseline vs time-varying covariates: Sex, age, adl and BMI were
  treated as baseline covariates; ABPET, and TAUPET were treated as
  time-varying, so their coefficients describe how changes in these
  measures over time are associated with changes in the probability of
  being in the worse CDRSB category.
\end{itemize}

\textbf{Results}

Using the marginal logistic GEE model with AR(1) working correlation, we
obtained the odds ratios shown in Table 1. After adjustment for sex,
age, BMI, ADL, ABPET and TAUPET, there was no clear evidence that time
alone was associated with the odds of worse cognition (OR 0.82, 95\% CI
0.54--1.25, p = 0.36). Sex, age, BMI and ADL also did not show strong
marginal associations with CDRSBbin (e.g.~sex: OR 0.91, 95\% CI
0.81--1.02, p = 0.10; age: OR 0.99, 95\% CI 0.98--1.00, p = 0.12).

For the biomarkers, the main effects of ABPET (OR 1.28, 95\% CI
0.87--1.86, p = 0.21) and TAUPET (OR 0.37, 95\% CI 0.12--1.18, p = 0.09)
at baseline were not statistically significant at the 5\% level. The
interaction between time and ABPET was also not significant (OR 0.93,
95\% CI 0.85--1.02, p = 0.14). In contrast, the time × TAUPET
interaction was statistically significant (OR 1.36, 95\% CI 1.09--1.70,
p \textless{} 0.01), indicating that the association between TAUPET and
the odds of worse cognition changes over time.

\textbf{Interpretation}

On average, afteradjusting for sex age and BMI,ADL did not show a
significant effect on whether a patient was in the worse-cognition
group. Amyloid PET (ABPET) also was not significantly related to worse
cognition or to how this changed over time. The important finding is tau
PET (TAUPET): the interaction between time and TAUPET was statistically
significant. This means that on average patients with higher tau values
are more likely to develop or keep worse cognition over time than
patients with lower tau, after accounting for the other factors. Higher
tau is linked to a faster worsening of cognition over follow-up, whereas
amyloid, ADL and the basic patient characteristics add no extra
information in this analysis.

\section{Question 2: Random-Effects Model
(GLMM)}\label{question-2-random-effects-model-glmm}

To estimate how the probability of being in the worse cognitive category
(CDRSBbin = 1, i.e.~CDRSB \textgreater{} 10) changes over time while
adjusting for patient characteristics, we fitted a generalized linear
mixed model (GLMM) with a logit link. The model included fixed effects
for time, sex, age, body mass index (BMI), activities of daily living
(ADL), amyloid PET (ABPET), and tau PET (TAUPET), and random intercepts
for both patients and trials to account for clustering within
individuals and study centres.

For patient \(i\ \) in trial \(j\ \) at time \(t\ \), let \$ Y\_\{ijt\}
= \text{CDRSBbin}\emph{\{ijt\} \$ be the binary outcome \$ Y}\{ijt\} = 1
\$ if CDRSB (\textgreater{} 10), (0) otherwise). We specify the GLMM
with logit link as:

\[
\begin{aligned}
\text{logit}\bigl\{\Pr(Y_{ijt} = 1 \mid b_{0i}, u_{0j})\bigr\}
&= \beta_0
+ \beta_1\,\text{time}_{ijt}
+ \beta_2\,\text{sex}_i
+ \beta_3\,\text{age}_i
+ \beta_4\,\text{bmi}_i \\
&\quad + \beta_5\,\text{adl}_i
+ \beta_6\,\text{abpet}_{ijt}
+ \beta_7\,\text{taupet}_{ijt}
+ b_{0i}
+ u_{0j}.
\end{aligned}
\]

where:

*\((\beta_0,\ldots, \beta_7)\) are population-level (fixed) effects,

\begin{itemize}
\item
  \(b_{0i} \sim N(0, \sigma_{b0}^2)\) is the patient-specific random
  intercept,
\item
  \(u_{0j} \sim N(0, \sigma_{u0}^2)\) is the trial-specific random
  intercept, conditional on \((b_{0i}, u_{0j})\) and the covariates,
  \((Y_{ijt} \sim \text{Bernoulli}(\pi_{ijt})\) with
  \((\pi_{ijt} = \Pr(Y_{ijt}=1 \mid b_{0i}, u_{0j})\).
\end{itemize}

\begin{verbatim}
Generalized linear mixed model fit by maximum likelihood (Laplace
  Approximation) [glmerMod]
 Family: binomial  ( logit )
Formula: 
CDRSBbin ~ time + sex + age + bmi + abpet + taupet + adl + time:abpet +  
    time:taupet + 1 + (time | patid)
   Data: alzheimer_long

      AIC       BIC    logLik -2*log(L)  df.resid 
     6578      6666     -3276      6552      6207 

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-2.277 -0.488 -0.169  0.469  2.526 

Random effects:
 Groups Name        Variance Std.Dev. Corr 
 patid  (Intercept) 31.30    5.59          
        time         1.76    1.33     -1.00
Number of obs: 6220, groups:  patid, 1253

Fixed effects:
            Estimate Std. Error z value Pr(>|z|)  
(Intercept)  0.28423    1.87027    0.15    0.879  
time        -0.05242    0.34520   -0.15    0.879  
sexFemale   -0.10433    0.08765   -1.19    0.234  
age         -0.01289    0.01157   -1.11    0.265  
bmi          0.01267    0.01982    0.64    0.523  
abpet       -0.00096    0.38547    0.00    0.998  
taupet      -1.63804    0.86573   -1.89    0.058 .
adl         -0.00494    0.01692   -0.29    0.770  
time:abpet  -0.04027    0.08830   -0.46    0.648  
time:taupet  0.42676    0.17447    2.45    0.014 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) time   sexFml age    bmi    abpet  taupet adl    tm:bpt
time        -0.860                                                        
sexFemale   -0.018 -0.024                                                 
age         -0.292 -0.023  0.033                                          
bmi         -0.312  0.002  0.023  0.088                                   
abpet       -0.166  0.307 -0.059 -0.263 -0.019                            
taupet      -0.749  0.784 -0.015 -0.101  0.002 -0.208                     
adl         -0.290  0.034  0.216  0.491  0.096 -0.038 -0.002              
time:abpet   0.233 -0.309  0.035  0.004  0.004 -0.918  0.230 -0.029       
time:taupet  0.712 -0.806  0.008  0.043  0.000  0.240 -0.944 -0.024 -0.293
optimizer (Nelder_Mead) convergence code: 0 (OK)
Model failed to converge with max|grad| = 1.78708 (tol = 0.002, component 1)
Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?
Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?
\end{verbatim}

\begin{table}
\caption{GLMM Model Results (Odds Ratios)}\tabularnewline

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lcccccc}
\toprule
effect & group & term & estimate & std.error & statistic & p.value\\
\midrule
fixed & NA & (Intercept) & 1.33 [0.03, 51.93] & 2.49 & 0.15 & 0.88\\
fixed & NA & time & 0.95 [0.48, 1.87] & 0.33 & -0.15 & 0.88\\
fixed & NA & sexFemale & 0.90 [0.76, 1.07] & 0.08 & -1.19 & 0.23\\
fixed & NA & age & 0.99 [0.97, 1.01] & 0.01 & -1.11 & 0.27\\
fixed & NA & bmi & 1.01 [0.97, 1.05] & 0.02 & 0.64 & 0.52\\
\addlinespace
fixed & NA & abpet & 1.00 [0.47, 2.13] & 0.39 & 0.00 & 1.00\\
fixed & NA & taupet & 0.19 [0.04, 1.06] & 0.17 & -1.89 & 0.06\\
fixed & NA & adl & 1.00 [0.96, 1.03] & 0.02 & -0.29 & 0.77\\
fixed & NA & time:abpet & 0.96 [0.81, 1.14] & 0.08 & -0.46 & 0.65\\
fixed & NA & time:taupet & 1.53 [1.09, 2.16] & 0.27 & 2.45 & 0.01\\
\addlinespace
ran\_pars & patid & sd\_\_(Intercept) & 5.59 & NA & NA & NA\\
ran\_pars & patid & cor\_\_(Intercept).time & -1.00 & NA & NA & NA\\
ran\_pars & patid & sd\_\_time & 1.33 & NA & NA & NA\\
\bottomrule
\end{tabular}}
\endgroup{}
\end{table}

\begin{table}

\caption{\label{tbl-glmm-ranef}GLMM Random Effects Variance Components}

\centering{

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lllrrr}
\toprule
  & Groups & Name & Variance & Std.Dev. & Corr\\
\midrule
(Intercept) & patid & (Intercept) & 31.298 & 5.594 & NA\\
time & patid & time & 1.762 & 1.327 & -0.9971\\
1 & Residual &  & 1.000 & 1.000 & NA\\
\bottomrule
\end{tabular}}
\endgroup{}

}

\end{table}%

\textbf{Model Motivation}

We fitted a logistic GLMM because the outcome (CDRSB) was binary and our
primary interest was in subject-specific effects and heterogeneity
between patients and sites. The model addresses the question: for a
given patient, how does the risk of worse cognition change over time,
after accounting for between-patient and between-trial differences?
Random intercepts for patients and trials capture variation in baseline
CDRSB risk at both levels and induce appropriate within-patient and
within-trial correlation. This parameterisation provides
patient-specific predictions and empirical Bayes estimates of individual
intercepts, while accommodating unequal numbers of visits per patient
and trial-level effects.

\textbf{Choice of Techniques and Estimation}

To analyse the longitudinal binary outcome CDRSBbin, we used a
generalised linear mixed model (GLMM) with a logit link. The model
included a random intercept for each patient (to allow each person to
have their own baseline risk) and a random intercept for trial (to
capture systematic differences between study sites/centres). This gives
a subject-specific model that accounts for the correlation of repeated
measurements within patients and clustering within trials. The model was
fitted by maximum likelihood using the Laplace approximation (via
glmer(\ldots, nAGQ = 1)), which approximates the integral over the
random effects and provides more accurate estimates for binary data than
quasi-likelihood methods such as PQL or MQL.

\textbf{Assumptions}

Let \(i\) index patients, \(j\) index trials, and \(t\) index
measurements within patient \(i\) in trial \(j\).

\begin{itemize}
\tightlist
\item
  Conditional on covariates and random effects, the responses are
  independent Bernoulli:
\end{itemize}

\[
Y_{ijt} \mid b_i, u_j \sim \mathrm{Bernoulli}(\pi_{ijt}),
\quad 
\pi_{ijt} = \Pr(Y_{ijt} = 1 \mid X_{ijt}, b_i, u_j),
\]

with

\[
\mathrm{logit}(\pi_{ijt}) = X_{ijt}^\top \beta + b_i + u_j.
\]

\begin{itemize}
\tightlist
\item
  Random intercepts for patient and trial are specified as
\end{itemize}

\[
b_i \sim N(0, \sigma_b^2), 
\quad
u_j \sim N(0, \sigma_u^2),
\]

where \(\{b_i\}\) are independent across patients, \(\{u_j\}\) are
independent across trials, and \(b_i\) is independent of \(u_j\).

\begin{itemize}
\item
  Link function and covariate effects:
\item
  The logit link is correctly specified for the conditional mean:

  \[
  \mathrm{logit}(\pi_{ijt}) = X_{ijt}^\top \beta + b_i + u_j.
  \]
\item
  The effects of continuous covariates are approximately linear on the
  logit scale, or otherwise correctly modelle.
\item
  Missing data:
\item
  Missing outcome data are assumed to be at least Missing At Random
  (MAR) given observed covariates, observed outcome history, and the
  random effects.
\end{itemize}

\textbf{Advantages}

\begin{itemize}
\tightlist
\item
  Estimates conditional (subject-specific) effects on the log-odds
  scale, aligning with questions about individual patient risk
  trajectories.
\item
  Random intercepts for patients and trials account for unobserved
  heterogeneity and induce appropriate within-patient and within-trial
  correlation.
\item
  Handles unequal numbers of visits and irregular visit patterns
  naturally.
\item
  Empirical Bayes estimates of random intercepts provide
  patient-specific predictions hence improving predictions.
\end{itemize}

\textbf{Disadvantages and potential problems}

\begin{itemize}
\tightlist
\item
  Parameters are subject-specific and not directly comparable to
  marginal (population-averaged) effects.
\item
  Sensitivity to model specification: Misspecification of the
  random-effects structure (e.g.~omitting important random slopes) or
  functional form of covariates can lead to biased inference.
\end{itemize}

\textbf{Reflection on parameterization}

We specified a logistic GLMM with a logit link and random intercepts for
patients and trials:

\[
\text{logit}\{\pi_{ijt}\} = X_{ijt}^\top \beta + b_i + u_j.
\]

This parameterisation yields subject-specific log-odds ratios, which
aligns with our interest in modelling individual risk rather than
marginal (population-averaged) effects. Random intercepts for patients
and trials account for unobserved heterogeneity and induce
within-patient and within-trial correlation, while remaining
parsimonious and numerically stable given the available data. Continuous
covariates were entered linearly on the logit scale, representing a
balance between model flexibility and interpretability; more flexible
forms could be considered if strong non-linearity were empirically
indicated.

\textbf{Results}

We fitted a generalized linear mixed model with a logit link for the
binary outcome CDRSBbin (0: CDRSB ≤ 10, 1: CDRSB \textgreater{} 10),
including fixed effects for time, sex, age, BMI, ADL, ABPET, and TAUPET,
and random intercepts for patient and trial. The model had AIC = 7822
and BIC = 7889, with log-likelihood = --3901 (--2·logLik = 7802) based
on 6220 observations (1253 patients, 25 trials). The estimated
random-intercept variances were very small for both patient (variance
2.16×10⁻¹⁵, SD 4.64×10⁻⁸) and trial (variance 2.25×10⁻¹⁵, SD 4.75×10⁻⁸),
indicating a boundary (singular) fit.

Fixed-effect estimates (log-odds scale) were: intercept --1.42 (SE 0.63,
z = --2.25, p = 0.024), time 0.25 (SE 0.016, z = 16.12, p \textless{}
0.001), sex (female vs male) --0.10 (SE 0.057, z = --1.66, p = 0.096),
age --0.013 (SE 0.0075, z = --1.79, p = 0.073), BMI 0.010 (SE 0.0129, z
= 0.79, p = 0.430), ADL --0.0029 (SE 0.0115, z = --0.25, p = 0.799),
ABPET 0.036 (SE 0.0966, z = 0.37, p = 0.709), and TAUPET 0.33 (SE 0.177,
z = 1.88, p = 0.060).

\textbf{Interpretation}

In this analysis, we modelled the probability of being in the worse
cognitive category (CDRSB \textgreater{} 10) over time, accounting for
repeated measurements within patients and across trials. Statistically,
the main strong signal is that the chance of worse cognitive status
increases over follow-up time. Other patient characteristics (sex, age,
BMI, daily functioning, and PET biomarkers) did not show clearly
independent effects in this model, and the random-effects part
contributed very small part, meaning most of the variation is explained
at the overall population level rather than by systematic differences
between individual patients or trials.

\subsection{Empirical Bayes
Predictions}\label{empirical-bayes-predictions}

Examine the empirical Bayes predictions (random effects) to identify
subjects with specific profiles.

\begin{figure}[H]

{\centering \includegraphics{lda_homework2_2025_files/figure-pdf/eb-predictions-1.pdf}

}

\caption{Empirical Bayes Predictions of Random Effects}

\end{figure}%

\begin{table}
\caption{Subjects with Highest Random Intercepts (High Risk)}\tabularnewline

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lcc}
\toprule
patid & random\_intercept & time\\
\midrule
220065 & 8.289 & -1.933\\
60050 & 8.189 & -1.912\\
70038 & 8.161 & -1.907\\
110008 & 8.145 & -1.907\\
170048 & 8.136 & -1.905\\
\addlinespace
90006 & 8.119 & -1.902\\
10025 & 8.107 & -1.899\\
240040 & 8.102 & -1.899\\
250021 & 8.095 & -1.897\\
250012 & 8.091 & -1.897\\
\bottomrule
\end{tabular}}
\endgroup{}
\end{table}

\begin{table}
\caption{Subjects with Lowest Random Intercepts (Low Risk)}\tabularnewline

\centering\begingroup\fontsize{9}{11}\selectfont

\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}{lcc}
\toprule
patid & random\_intercept & time\\
\midrule
100011 & -4.735 & 1.136\\
20004 & -4.718 & 1.130\\
210024 & -4.680 & 1.120\\
70025 & -4.655 & 1.116\\
50080 & -4.584 & 1.097\\
\addlinespace
70053 & -4.552 & 1.086\\
190010 & -4.517 & 1.080\\
50017 & -4.512 & 1.082\\
90029 & -4.504 & 1.078\\
40010 & -4.484 & 1.071\\
\bottomrule
\end{tabular}}
\endgroup{}
\end{table}

Left panel (patient random intercepts) Each bar shows how many patients
have a given ``patient effect'' on the log-odds of being in the worse
CDRSB category, after adjusting for time, sex, age, BMI, ADL, amyloid
and tau. All the bars are very tightly clustered around 0, and the range
is extremely small (on the order of 10⁻¹³). This means that, once we
account for the measured covariates, the model estimates almost no
residual between-patient difference in baseline risk. Patients'
individual intercepts are essentially the same.

Right panel(trial random intercepts) Each dot is a trial (centre),
showing how much its baseline log-odds deviates from the overall
average. All trials lie almost exactly on the vertical line at 0, again
with tiny deviations (order 10⁻¹⁵). This indicates no meaningful
between-trial/site variability in baseline risk after covariate
adjustment.

In summary, empirical Bayes predictions suggest that, in this GLMM,
nearly all of the variation in baseline probability of ``worse CDRSB''
is captured by the fixed effects, and there is negligible leftover
variation attributable to individual patients or trial sites.




\end{document}
